apiVersion: v1
kind: Service
metadata:
  name: astraops-backend
  namespace: astraops
spec:
  type: ClusterIP
  selector:
    app: astraops-backend
  ports:
    - name: http
      port: 80
      targetPort: 5002
