import { FastifyInstance } from "fastify";
import { authenticate, requireRole } from "../../lib/auth";
import { finopsService } from "../finops/finops.service";
import { attachFinopsListener } from "../finops/finops.stream";
import { aiCfoService } from "../ai-cfo/ai-cfo.service";
import { billingService } from "../billing/billing.service";

export async function costRoutes(app: FastifyInstance) {
  app.addHook("preHandler", authenticate);

  app.post("/analyze", { preHandler: requireRole(["admin", "operator", "viewer"]) }, async () => {
    const [anomaly, predict, records] = await Promise.all([
      finopsService.anomaly(),
      finopsService.predict(),
      finopsService.cost(),
    ]);
    const monthlySpend = Math.round(records.reduce((sum, r) => sum + Number((r as any).amountUsd ?? 0), 0));
    const forecast = Math.round(monthlySpend * (1 + Number((predict as any)?.growthRate ?? 0.12)));
    const savings = Math.max(0, Math.round(monthlySpend * 0.18));
    const risk = (anomaly as any)?.anomaly ? "HIGH" : monthlySpend > 3000 ? "MEDIUM" : "LOW";
    const out = {
      monthlySpend,
      forecastedSpend: forecast,
      savingsIdentified: savings,
      riskLevel: risk,
      aiConfidence: risk === "HIGH" ? 91 : 86,
      anomaly,
      prediction: predict,
      records,
    };
    aiCfoService.emitUpdate("ai_cfo_cost_analyze", out as unknown as Record<string, unknown>);
    return out;
  });

  app.post("/fix", { preHandler: requireRole(["admin", "operator"]) }, async (request) => {
    const optimized = await finopsService.optimize();
    const enforced = await finopsService.enforce({});
    const records = await finopsService.cost();
    const beforeCostUsd = Math.round(records.reduce((sum, r) => sum + Number((r as any).amountUsd ?? 0), 0));
    const estimatedSavings = Math.round((optimized as any)?.monthlySavingsUsd ?? 420);
    const afterCostUsd = Math.max(0, beforeCostUsd - estimatedSavings);
    const actions = [
      "Scaled down idle workloads",
      "Applied spot-instance profile",
      "Reduced over-provisioned CPU limits",
      "Cleaned unused volumes and snapshots",
    ];
    const savingsEntry = billingService.recordSavings({
      tenantId: String((request as any)?.scopeContext?.orgId ?? "org-1"),
      userId: String((request as any)?.authUser?.id ?? "system-ai-cfo"),
      beforeCostUsd,
      afterCostUsd,
      explanation: "Savings generated by AI optimization actions after anomaly detection and policy enforcement.",
      actions,
    });
    const out = {
      actionsPerformed: actions,
      savingsAchieved: estimatedSavings,
      explainability: {
        beforeCostUsd,
        afterCostUsd,
        savingsUsd: savingsEntry.savingsUsd,
        platformFeeUsd: savingsEntry.platformFeeUsd,
        netSavingsUsd: savingsEntry.netSavingsUsd,
        explanation: savingsEntry.explanation,
      },
      optimization: optimized,
      enforcement: enforced,
    };
    aiCfoService.emitUpdate("ai_cfo_cost_fix", out as unknown as Record<string, unknown>);
    return out;
  });

  app.get("/stream", { preHandler: requireRole(["admin", "operator", "viewer"]) }, async (request, reply) => {
    reply.raw.setHeader("Content-Type", "text/event-stream");
    reply.raw.setHeader("Cache-Control", "no-cache, no-transform");
    reply.raw.setHeader("Connection", "keep-alive");
    reply.raw.setHeader("X-Accel-Buffering", "no");
    reply.raw.flushHeaders?.();

    const write = (payload: Record<string, unknown>) => {
      reply.raw.write("event: update\n");
      reply.raw.write(`data: ${JSON.stringify(payload)}\n\n`);
    };
    write({ type: "cost_stream_ready", ts: Date.now() });
    const hb = setInterval(() => write({ type: "heartbeat", ts: Date.now() }), 15000);
    const detachFinops = attachFinopsListener((event) => write(event));
    const detachCfo = aiCfoService.subscribe((event) => write(event as unknown as Record<string, unknown>));

    request.raw.on("close", () => {
      clearInterval(hb);
      detachFinops();
      detachCfo();
    });
    return reply;
  });
}

